name: Python CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
        - '3.12'
        toxenv: [celery54-django52]

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: setup python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
      with:
        mongodb-version: 4.0

    - name: Install pip and pip-tools
      run: pip install -r requirements/pip-tools.txt

    - name: Install Dependencies
      run: make test.setup install

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
