name: Python CI

on:
  workflow_call:
  pull_request:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
        - '3.12'
        toxenv: [django52]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
      with:
        mongodb-version: 4.0

    - name: Install Dependencies
      run: uv sync --group ci

    - name: Run Tests
      run: uv run tox -e ${{ matrix.toxenv }}
